FROM fedora

# COPY   folder3/file2 /container/folder 
# COPY  /folder3/file2 /container/folder
# COPY ./folder3/file2 /container/folder

COPY /file1  /container/folder

# COPY ./folder3/../file3 /container/folder
# COPY ../folder2/file3 /container
